### PR TITLE
Initial data insertion.

### PR DESCRIPTION
**Pull request by altayhunoglu**
With the help of this configuration, we can execute initial SQL codes. 
For example, we add some insertion codes in the `data.sql` file for the `roles` table:

```sql
INSERT INTO roles (name) VALUES ('ROLE_USER');
INSERT INTO roles (name) VALUES ('ROLE_MODERATOR');
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');
```

As a result, on database creation, this SQL code will be executed just once and role lookup table will be populated with these default values:

image

### CODE REVIEW

**Comment by ErdemT09** [comment]
Is data.sql a default file that Spring automatically renders or is it configured somewhere?
Would it also be run if we rename it to something else like `my_queries.sql`?

**Comment by altayhunoglu** [comment]
> Is data.sql a default file that Spring automatically renders or is it configured somewhere?
> 
> Would it also be run if we rename it to something else like `my_queries.sql`?


Nice question Erdem. It is a default file but I am sure we can also rename the file with some other configuration.

**Comment by ErdemT09** [comment]
https://www.baeldung.com/spring-boot-data-sql-and-schema-sql

**Review by ErdemT09 — APPROVED** [review]

**Comment by altayhunoglu** [comment]
Yes, Baeldung is a reliable resource.

**Pull request merged**
